'use client'

import './globals.css'
import { Inter } from 'next/font/google'

import Header from './Header'
import { Container } from '@mui/material'
import { ApolloClient, ApolloProvider } from '@apollo/client'
import { InMemoryCache } from '@apollo/client/cache'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const client = new ApolloClient({
  uri: 'http://localhost:4000/graphql',
  cache: new InMemoryCache()
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <Container>
            <Header />
            {children}
          </Container>
        </ApolloProvider>
      </body>
    </html>
  )
}
